name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version tag
        id: extract_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/roble-api:latest -t ${{ secrets.DOCKER_USERNAME }}/roble-api:${{ env.VERSION }} . 
          docker push ${{ secrets.DOCKER_USERNAME }}/roble-api:latest 
          docker push ${{ secrets.DOCKER_USERNAME }}/roble-api:${{ env.VERSION }}
